Add verification for join.epg file creation
Added a verification step to check if 'join.epg' file is created by the Python script.

diff --git a/.github/workflows/update_epg.yml b/.github/workflows/update_epg.yml
--- a/.github/workflows/update_epg.yml
+++ b/.github/workflows/update_epg.yml
@@ -9,7 +9,7 @@ jobs:
   build:
     runs-on: ubuntu-latest
     permissions:
-      contents: write # Permesso di scrittura esplicito
+      contents: write
 
     steps:
       - name: Checkout repository
@@ -26,9 +26,19 @@ jobs:
       - name: Run merge script
         run: python merge_epg.py
 
+      - name: Verificata creazione file
+        run: |
+          if [ -f "join.epg" ]; then
+            echo "Il file join.epg esiste ed è pronto."
+            ls -lh join.epg
+          else
+            echo "Errore: Il file join.epg non è stato creato dallo script Python."
+            exit 1
+          fi
+
       - name: Commit and push changes
         uses: stefanzweifel/git-auto-commit-action@v5
         with:
           commit_message: "Update EPG automatico"
           file_pattern: 'join.epg'
-          status_options: '--untracked-files=no'
+          # Abbiamo tolto status_options per permettere l'invio di nuovi file
